services:
  xiaoxue-wol:
    build: .
    container_name: xiaoxue-wol
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - WOM_WEB_PORT=39090
      - WOM_ADMIN_USERNAME=admin
      - WOM_ADMIN_PASSWORD=admin
      - WOM_SECRET_KEY=please-change-this-secret-key
