services:
  wol-xyz:
    image: xueayis/wol-xyz:latest
    build: .
    container_name: wol-xyz
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - WEB_PORT=39090
      - TZ=Asia/Shanghai
